export default[
    {
        name:"Mid1",
        type:"Bleu",
        declinaison1:"./Assets/Affiches/bleu2-V1.jpeg",
        declinaison2:"./Assets/Affiches/bleu2-V2.jpeg",
        declinaison3:"./Assets/Affiches/bleu2-V3.jpeg",
    },
    {
        name:"Fascho1",
        type:"Rouge",
        declinaison1:"./Assets/Affiches/rouge2-V1.jpeg",
        declinaison2:"./Assets/Affiches/rouge2-V2.jpeg",
        declinaison3:"./Assets/Affiches/rouge2-V3.jpeg",
    },
    {
        name:"Ecolo1",
        type:"Vert",
        declinaison1:"./Assets/Affiches/vert1-v1.jpeg",
        declinaison2:"./Assets/Affiches/vert1-v2.jpeg",
        declinaison3:"./Assets/Affiches/vert1-v3.jpeg",
    },
    {
        name:"Mid2",
        type:"Bleu",
        declinaison1:"./Assets/Affiches/bleu3-V1.jpeg",
        declinaison2:"./Assets/Affiches/bleu3-V1.jpeg",
        declinaison3:"./Assets/Affiches/bleu3-V1.jpeg",
    },
    {
        name:"Fascho2",
        type:"Rouge",
        declinaison1:"./Assets/Affiches/rouge3-V1.jpeg",
        declinaison2:"./Assets/Affiches/rouge3-V2.jpeg",
        declinaison3:"./Assets/Affiches/rouge3-V3.jpeg",
    },
    {
        name:"Ecolo2",
        type:"Vert",
        declinaison1:"./Assets/Affiches/vert2-V1.jpeg",
        declinaison2:"./Assets/Affiches/vert2-V2.jpeg",
        declinaison3:"./Assets/Affiches/vert2-V3.jpeg",
    },
    {
        name:"Mid3",
        type:"Bleu",
        declinaison1:"./Assets/Affiches/bleu2-V2.jpeg",
        declinaison2:"./Assets/Affiches/bleu2-V2.jpeg",
        declinaison3:"./Assets/Affiches/bleu2-V2.jpeg",
    },
    {
        name:"Fascho3",
        type:"Rouge",
        declinaison1:"./Assets/Affiches/rouge1-V1.jpeg",
        declinaison2:"./Assets/Affiches/rouge1-V2.jpeg",
        declinaison3:"./Assets/Affiches/rouge1-V3.jpeg",
    },

]